web/board/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.board, name='board'),
    path('<int:pk>',views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/',views.create, name="create"),
    path('<int:pk>/remove/', views.remove, name='remove'),
    path('<int:pk>/update/', views.update, name='update'),
    path('download/<int:pk>/', views.download_file, name='download'),

]

web/board/models.py
from django.db import models

class Post(models.Model):
    author = models.CharField(max_length=10)
    subject = models.CharField(max_length=20)
    body = models.CharField(max_length=250)
    file = models.FileField(upload_to='media/')
    createDate = models.DateTimeField(auto_now_add=True)
    updateDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.body}'

web/board/views.py
from django.shortcuts import redirect, render
from .models import Post
from django.utils import timezone 
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
import os


@login_required(login_url='/')
def board(request):
    posts = Post.objects.all()
    
    context = {
        'posts': posts  
    }
    return render(request, 'board.html', context)


@login_required(login_url='/')
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    context = {
        'post': post
    }
    return render(request, 'detail.html', context)


@login_required(login_url='/')
def new(request):
    return render(request, 'new.html')


@login_required(login_url='/')
def create(request):
    author = request.POST['author']
    subject = request.POST['subject']
    body = request.POST['body']
    
    if 'file' in request.FILES:  # 파일이 업로드되었는지 확인
        file = request.FILES['file']
    else:
        file = None
    
    post = Post(author=author, subject=subject, body=body, file=file, createDate=timezone.now())
    post.save()
    return redirect('board:detail', pk=post.pk)


@login_required(login_url='/')
def remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('board:board')
    return render(request, 'remove.html', {'post': post})


@login_required(login_url='/')
def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        author = request.POST['author']
        subject = request.POST['subject']
        body = request.POST['body']
        
        if 'file' in request.FILES:  # 파일이 업로드되었는지 확인
            file = request.FILES['file']
        else:
            file = post.file  # 기존 파일 유지
        
        # 필요한 필드들을 업데이트
        post.author = author
        post.subject = subject
        post.body = body
        post.file = file
        post.save()
        return redirect('board:detail', pk=post.pk)

    context = {
        'post': post
    }
    return render(request, 'update.html', context)

@login_required(login_url='/')
def download_file(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.file:
        file_path = os.path.join('media', os.path.basename(post.file.name))
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
    else:
        raise Http404("The requested file does not exist.")

web/board/templates/board.html
{% load static %}

<style>
    @import 'https://fonts.googleapis.com/css?family=Open+Sans:600,700';

    * {
        font-family: 'Open Sans', sans-serif;
    }

    .rwd-table {
        margin: auto;
        min-width: 300px;
        max-width: 100%;
        border-collapse: collapse;
        color: #333;
        border-radius: .4em;
        overflow: hidden;
    }

    .rwd-table tr:first-child {
        border-top: none;
        background: #1e88ff;
        color: #fff;
    }

    .rwd-table tr {
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        background-color: #f5f9fc;
    }

    .rwd-table tr:nth-child(odd):not(:first-child) {
        background-color: #ebf3f9;
    }

    .rwd-table th {
        display: none;
        text-align: center;

    }

    .rwd-table td {
        display: block;
        text-align: center;
        width: 300px;
    }

    .rwd-table td:first-child {
        margin-top: .5em;
        width: 500px;
        text-align: center;
    }

    .rwd-table td:before {
        content: attr(data-th) ": ";
        font-weight: bold;
        width: 120px;
        display: inline-block;
        color: #000;
        text-align: left;
    }

    @media screen and (min-width: 600px) {
        .rwd-table td {
            display: table-cell;
            text-align: center;
            vertical-align: middle;
        }

        .rwd-table th,
        .rwd-table td {
            padding: 1em;
        }
    }

    @media screen and (max-width: 601px) {
        .rwd-table tr:nth-child(2) {
            border-top: none;
        }
    }

    @media screen and (min-width: 600px) {
        .rwd-table tr:hover:not(:first-child) {
            background-color: #d8e7f3;
        }

        .rwd-table a {
            text-decoration: none;
        }

        .rwd-table td:before {
            display: none;
        }

        .rwd-table th,
        .rwd-table td {
            display: table-cell;
            padding: .25em .5em;
        }

        .rwd-table th:first-child,
        .rwd-table td:first-child {
            padding-left: 0;
        }

        .rwd-table td:first-child a {
            color: black;
        }

        .rwd-table td:first-child a:visited {
            color: inherit;
        }

        .rwd-table th:last-child,
        .rwd-table td:last-child {
            padding-right: 0;
        }

        .rwd-table th,
        .rwd-table td {
            padding: 1em !important;
        }
    }


    body {
        background-color: #f5f5f5;
    }

    h1 {
        text-align: center;
        font-size: 2.4em;
        color: #1e88ff;
    }

    .container {
        display: block;
        text-align: center;
    }

    h3_board {
        display: inline-block;
        position: relative;
        text-align: center;
        font-size: 1.5em;
        color: #cecece;
    }

    h3_board:before {
        content: "\25C0";
        position: absolute;
        left: -50px;
        -webkit-animation: leftRight 2s linear infinite;
        animation: leftRight 2s linear infinite;
    }

    h3_board:after {
        content: "\25b6";
        position: absolute;
        right: -50px;
        -webkit-animation: leftRight 2s linear infinite reverse;
        animation: leftRight 2s linear infinite reverse;
    }

    .btn-container {
        text-align: center;
        margin-top: 1em;
    }

    .btn-container a {
        display: inline-block;
        padding: 1em 2em;
        background-color: #1e88ff;
        color: #fff;
        text-decoration: none;
        border-radius: 10px;
        transition: background-color 0.3s;
        float: right;
        margin-right: 20px;
    }

    .btn-container a:hover {
        background-color: #3071a9;
    }
</style>



<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="favicon.png">

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap5" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">

    <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

    <title>DocDoc</title>
</head>

<body>

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close">
                <span class="icofont-close js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>


    <nav class="site-nav" style="padding-top: 10px;">
        <div class="container">
            <form action="{% url 'login:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-link" style="left: 47%;">
                    <i class="bi bi-box-arrow-in-right" style="color: grey; font-size: 30px;line-height: 22px;"></i>
                </button>
            </form>
            <div class="menu-bg-wrap">
                <div class="site-navigation">
                    <a href="/main" class="logo m-0 float-start">DOCDOC</a>
                    <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                        <li><a href="/main">Home</a></li>
                        <li><a href="/about">About</a></li>
                        <li class="has-children" id="service-menu">
                            <a href="#">Service</a>
                            <ul class="dropdown">
                                <li><a href="/submit">Submit</a></li>
                                <li><a href="/search_main">Search</a></li>
                            </ul>
                        </li>
                        <li class="active"><a href="/board">Board</a></li>
                        <li><a href="/contact">Contact Us</a></li>
                    </ul>

                    <a href="#"
                        class="burger light me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none"
                        data-toggle="collapse" data-target="#main-navbar">
                    </a>

                </div>
            </div>
        </div>
    </nav>


    <div class="section">
        <br><br><br><br>
        <div class="container">
            <h1 class="blue-text" style="padding: 20px;">Notice Board</h1>

            <table class="rwd-table">
                <tr>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성 날짜</th>
                </tr>

                {% for col in posts reversed %}
                <tr>
                    <td data-th="제목"><a href="{% url 'board:detail' col.pk %}">{{ col.subject }}</a></td>
                    <td data-th="작성자">{{ col.author }}</td>
                    <td data-th="날짜">{{ col.createDate|date:"Y.m.d" }}</td>
                </tr>
                {% endfor %}
            </table>

            {% if user.is_staff %}
            <div class="btn-container">
                <a href="{% url 'board:new' %}">글쓰기</a>
            </div>
            {% endif %}


            <div class="container">
            </div>
        </div>
    </div>

    <div class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4" style="width: 50%;">
                    <div class="widget">
                        <h3>Contact</h3>
                        <address>15, Mudeung-ro 202beon-gil, Buk-gu,
                            Gwangju, Republic of Korea</address>
                    </div>
                </div>
                <div class="col-lg-4" style="width: 50%;">
                    <div class="widget">
                        <h3>Sources</h3>
                        <ul style="display: flex; justify-content: space-between; padding:0px; ">
                            <p><a href="/about">About us</a></p>
                            <p><a href="/submit">Submit</a></p>
                            <p><a href="/search">Search</a></p>
                            <p><a href="/board">Board</a></p>
                            <p><a href="/contact">Contact us</a></p>
                            <p><a href="/use_acc">Privacy</a></p>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-12 text-center">
                    <!-- 
                **==========
                NOTE: 
                Please don't remove this copyright link unless you buy the license here https://untree.co/license/  
                **==========
              -->

                    <p>Copyright KT &copy;
                        <script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash;
                        Designed with love by <a href="https://untree.co">Untree.co</a>
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tiny-slider.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/counter.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script>
        // Service 메뉴 클릭 시 이벤트 처리
        document.getElementById("service-menu").addEventListener("click", function (event) {
            event.preventDefault(); // 링크 이동을 막음
        });
    </script>
</body>

</html>

web/board/templates/detail.html
{% load static %}
<style>
    body {
        font-family: "Montserrat", sans-serif;
        margin: 0;
        padding: 0;
    }

    header {
        height: 100px;
        text-align: right;
        color: white;
        margin-left: 20px;
        margin-right: 20px;
    }

    header>.wrap>ul {
        float: right;
        font-size: 25px;
    }

    @import 'https://fonts.googleapis.com/css?family=Open+Sans:600,700';

    * {
        font-family: 'Open Sans', sans-serif;
    }

    h1 {
        font-weight: bold;
        text-align: center;
        font-size: 2.4em;
        color: #1e88ff;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 2em;
    }

    label {
        font-weight: bold;
        margin-bottom: 0.5em;
    }

    input[type="text"],
    textarea {
        height : 30px;
        width: 800px;
        padding: 0.5em;
        border: 1px solid #ddd;
        border-radius: 4px;
        margin-bottom: 1em;
    }
    textarea {
        height: 500px;
    }

    .input-container {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        margin-bottom: 1em;
    }

    .input-container label {
        order: -1;
        margin-bottom: 0;
    }

    

    .button_s[type="submit"] {
        padding: 0.8em 2em;
        background-color: #1e88ff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
        margin-top: 1em;
    }

    .button_s[type="submit"]:hover {
        background-color: #3071a9;
    }

    
    
</style>

<!DOCTYPE html>
<html lang="en">
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Untree.co">
        <link rel="shortcut icon" href="favicon.png">
    
        <meta name="description" content="" />
        <meta name="keywords" content="bootstrap, bootstrap5" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    
    
        <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    
        <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
    
        <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    
        <title>DocDoc</title>
    </head>
    <body>
    
        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close">
                    <span class="icofont-close js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>
    
        
        <nav class="site-nav" style="padding-top: 0px;">
            <div class="container">
              <form action="{% url 'login:logout' %}" method="post">
                 {% csrf_token %}
                 <button type="submit" class="btn btn-link" style="left: 47%;">
                   <i class="bi bi-box-arrow-in-right" style="color: grey; font-size: 30px;line-height: 22px;"></i>
                 </button>
              </form>
                <div class="menu-bg-wrap">
                    <div class="site-navigation">
                        <a href="/main" class="logo m-0 float-start">DOCDOC</a>
                        <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
                            <li><a href="/main">Home</a></li>
                       <li><a href="/about">About</a></li>
                            <li class="has-children" id="service-menu">
                          <a href="#">Service</a>
                          <ul class="dropdown">
                              <li><a href="/submit">Submit</a></li>
                              <li><a href="/search_main">Search</a></li>                                
                          </ul>
                      </li>
                            <li class="active"><a href="/board">Board</a></li>
                            <li><a href="/contact">Contact Us</a></li>
                        </ul>
        
                        
                        
        
                    </div>
                </div>
            </div>
        </nav>
    
    
        <div class="section">
            <br><br><br><br>
            <div class="container">    
                <h1 class="blue-text" style="padding: 20px;">Notice Board</h1>
    <form action="{% url 'board:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-container">
            <label for="author">작성자</label>
            <input type="text" id="author" name="author" value="{{ request.user.username }}" readonly>
        </div>
        <div class="input-container">
            <label for="subject">제목</label>
            <input type="text" id="subject" name="subject">
        </div>
        <div class="input-container">
            <label for="body">내용</label>
            <textarea id="body" name="body"></textarea>
        </div>
        <div class="input-container" style="margin-right: 550px;">
                <label for="file">첨부파일</label>
                <input type="file" id="file" name="file">
            </div>
        
        <button type="submit" class="button_s">작성하기</button>
    </form>
    
    <div class="container">
        <h3></h3>
    </div>
    </div>
</div> <!-- /.untree_co-section -->

<div class="site-footer">
    <div class="container">
       
       <div class="row">
          <div class="col-lg-4" style="width: 50%;" >
             <div class="widget" >
                <h3>Contact</h3>
                <address>15, Mudeung-ro 202beon-gil, Buk-gu,
                   Gwangju, Republic of Korea</address>
             </div> <!-- /.widget -->
          </div> <!-- /.col-lg-4 -->
          <div class="col-lg-4" style="width: 50%;">
             <div class="widget">
                <h3>Sources</h3>
                <ul style="display: flex; justify-content: space-between; padding:0px; ">
                   <p><a href="/about">About us</a></p>
                   <p><a href="/submit">Submit</a></p>
                   <p><a href="/search">Search</a></p>
                   <p><a href="/board">Board</a></p>
                   <p><a href="/contact">Contact us</a></p>
                   <p><a href="/use_acc">Privacy</a></p>
                </ul>
             </div> <!-- /.widget -->
          </div> <!-- /.col-lg-4 -->
       </div> <!-- /.row -->

       <div class="row mt-5">
          <div class="col-12 text-center">
             <!-- 
            **==========
            NOTE: 
            Please don't remove this copyright link unless you buy the license here https://untree.co/license/  
            **==========
          -->

          <p>Copyright KT &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> <!-- License information: https://untree.co/license/ -->
          </p>
        </div>
      </div>
    </div> <!-- /.container -->
  </div> <!-- /.site-footer -->


<!-- Preloader -->
<div id="overlayer"></div>
<div class="loader">
    <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
</div>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/navbar.js' %}"></script>
<script src="{% static 'js/counter.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script>
    // Service 메뉴 클릭 시 이벤트 처리
    document.getElementById("service-menu").addEventListener("click", function(event) {
        event.preventDefault(); // 링크 이동을 막음
    });
 </script>

</body>
</html>

web/board/templates/remove.html
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        padding: 20px;
    }
    form {
        background-color: #fff;
        padding: 20px;
        border: 1px solid #ccc;
        max-width: 400px;
        margin: 0 auto;
        text-align: center;
    }
    h3 {
        margin-bottom: 20px;
    }
    button {
        padding: 10px 20px;
        background-color: #1e88ff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    button:hover {
        background-color: #d32f2f;
    }
</style>

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>글 삭제</title>
</head>

<body>
    <form method="POST">
        {% csrf_token %}
        <h3>{{ post.postname }} 삭제 하시겠습니까?</h3>
        <button>삭제</button>
    </form>
</body>

</html>